routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('/clear_cache', function() {
        Artisan::call('cache:clear');
        Artisan::call('view:clear');
        Artisan::call('route:clear');
        Artisan::call('config:clear');
    });

    Auth::routes();
    Route::get('/home', 'HomeController@index')->name('home');
    Route::post('/login', 'Auth\LoginController@login');
    Route::get('/logout', 'Auth\LoginController@logout')->name('auth.logout');

    Route::get('/', 'HomeController@index')->name('home')->middleware('superAdmin');
    /*Route::get('/home', 'HomeController@index')->name('home')->middleware('superAdmin');*/

    Route::middleware('superAdmin')->prefix('admin')->name('admin.')->group(function () {
        Route::resources([
            'jobs' => 'JobController',
            'products' => 'ProductController',
            'users' => 'UserController',
            'vehicles'=>'VehiclesController',
        ]);
        Route::put('updatereview',"Notificationcontroller@updatereview")->name('review.edit');
        Route::put('updatepayment','InvoiceController@update')->name('payment.edit');
        Route::put('updatejob','JobController@update')->name('jobs.edit');
        Route::put('updateuser','UserController@updateuser')->name('users.edit');
        Route::put('updatevehicles','VehiclesController@updaterecord')->name('vehicles.edit');
        Route::post('updateuser/{id}','UserController@updateuser');
       // Route::get('edituser/{id}','UserController@edituser')->name('users.edit');
        Route::get('sendnotification/{id}','Notificationcontroller@sendtouser')->name('users.sendnotification');
        Route::post('user/otp', 'UserController@sendOTP');
        Route::get('sentnotifications','Notificationcontroller@sentnotifications')->name('sentnotifications');
        Route::post('user/reset-password', 'UserController@sendResetPassword');
        Route::post('jobs/status', 'JobController@changeStatus');
        Route::post('addvehicle','VehiclesController@addvehicle');
        Route::get('payments','PaymentController@index');
        Route::get('settings','UserController@getSettings');
        Route::post('settings', 'UserController@postSettings');
        Route::get('reviews','JobController@getReviews');
        Route::get('orders','ProductController@getOrders');
        Route::get('orders','OrderController@index');
        Route::get('notification','Notificationcontroller@index');
        Route::post('sendnotification','Notificationcontroller@save');
        Route::get('invoice','InvoiceController@view');
        Route::get('deleteincoice/{id}','InvoiceController@trash');
        Route::get('deletevehicle/{id}','VehiclesController@deletevehicle');
    });
    Route::get('/deletevehicle/{id}','VehiclesController@deletevehicle');
    Route::get('/Getvehicle/{id}','VehiclesController@Getvehicle');

    

app/Models/Job.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Job extends Model
{
    use SoftDeletes;
    //
    protected $table = "jobs";
    protected $fillable = [
        'delivery_address', 'delivery_latitude', 'delivery_longitude', 'description', 'expected_delivery_time',
        'geohash', 'item_category', 'job_address', 'job_latitude', 'job_longitude', 'job_price', 'package_size',
        'posted_at', 'priority', 'receiver_instructions', 'security_code', 'status', 'document_id', 'receiver_name', 'receiver_contact',
        'sender_id', 'receiver_id', 'source_address_appartment', 'delivery_address_appartment', 'distance'
    ];


    public function sender(){
        return $this->belongsTo('App\User');
    }

    public function receiver(){
        return $this->belongsTo('App\User');
    }

    public function jobstatus(){
        return $this->hasMany('App\Models\Jobstatus', 'job_id', 'id');
    }

    public function getPickupDateAttribute(){

        if($this->jobstatus()){
            $accepted = config('enums.job.status.ACCEPTED');
            $jobstatus = $this->jobstatus()->where('status', $accepted)->orderBy('id', 'desc')->first();
            if($jobstatus){
                return $jobstatus->created_at->format('m-d-Y h:i a');
            }else{
                return null;
            }
        }

        return null;
    }

    public function wallet(){
        return $this->hasOne('App\Models\Wallet', 'job_id', 'id');
    }

    public function jobprices(){
        return $this->hasOne('App\Models\jobprice', 'job_id', 'id');
    }

    public function getTotalRatingAttribute(){
        return Jobreview::where('job_id', $this->attributes['id'])->sum('rating');
    }

    public function getDriverReviewedAttribute(){
        return Jobreview::where('job_id', $this->attributes['id'])->sum('driver_reviewed');
    }

    public function getClientReviewedAttribute(){
        return Jobreview::where('job_id', $this->attributes['id'])->sum('client_reviewed');
    }
    function getorderdistance($id){
         return $this->all()->where('id','=',$id)->first();
      }





}

app/Http/Controllers/API/JobController.php
<?php

namespace App\Http\Controllers\API;

use App\Helpers\Geohash;
use App\Helpers\Helper;
use App\Helpers\PaypalHelper;
use App\Http\Controllers\Controller;
use App\Http\Resources\JobCollection;
use App\Http\Resources\JobResource;
use App\Http\Resources\JobreviewResource;
use App\Http\Resources\WalletCollection;
use App\Http\Resources\WalletResource;
use App\Models\Cash;
use App\Models\Invoice;
use App\Models\Job;
use App\Models\Jobreview;
use App\Models\Jobstatus;
use App\Models\Joburls;
use App\Models\Location;
use App\Models\OtpNumbers;
use App\Models\Settings;
use App\Models\Wallet;
use App\User;
use Carbon\Carbon;
use Dotenv\Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class JobController extends Controller
{

    // helper function
    private function updateJobStatus(Job $job, $latitude = null, $longitude = null){
        Jobstatus::create([
            'job_id' => $job->id,
            'receiver_id' => $job->receiver_id,
            'status' => $job->status,
            'latitude' => $latitude,
            'longitude' => $longitude,
        ]);

        $j = Job::where('id', $job->id)->first();
        if($j){
            $j->status = $job->status;
            $j->save();
        }

        // calc amount on status completed


    }

    public function apiAddJobs(Request $request){

        $data = $request->all();
        $jobs = $data['jobs'];

        foreach ($jobs as $job){

            try{
                // create type if not created
                Job::firstOrCreate([
                    'document_id' => $job['id']
                ], $job);

            } catch (\Exception $e){
                Log::error( $e->getLine() . " " .$e->getMessage());
                continue;
            }


        }

        return self::success('Jobs Updated');


    }

    public function nearbyJobs(Request $request){

        $user_id = \auth()->user()->id;
        $user = User::where('id', $user_id)->first();
        $data = $request->all();
//        $geohash = new Geohash();

        $location = $user->location;
        $latitude = isset($data['latitude']) ? $data['latitude'] : $location->latitude;
        $longitude = isset($data['longitude']) ? $data['longitude'] : $location->longitude;
        $distance = isset($location->distance) ? $location->distance : 25;
//        $bounds = $geohash->bounds($latitude, $longitude, $distance);
//        $bn = $geohash->getBoundsOfDistance($bounds['upper'], $bounds['lower']);


        // see the location filter in future
        $query = Job::query();
        $query->select('*');

//        $query->where('geohash', '<=', $bn['lower']);
//        $query->where('geohash', '>=', $bn['upper']);

        if(isset($data['vehicle_type'])){
            $sizes = $data['vehicle_type']; // collect($data['vehicle_type'])->values()->toArray();
            $query->whereIn('package_size', $sizes);
        }

        if(isset($data['item_category'])){
            $cats = $data['item_category']; // collect($data['vehicle_type'])->values()->toArray();
            $query->whereIn('item_category', $cats);
        }

        if(isset($data['job_price_between'])){
            $start = isset($data['job_price_between'][0]) ? $data['job_price_between'][0] : null;
            $end = isset($data['job_price_between'][1]) ? $data['job_price_between'][1] : null;

            if(isset($start)){
                $query->where('job_price', '>=', $start);
            }

            if(isset($end)){
                $query->where('job_price', '<=', $end);
            }
        }

        $query->addSelect( DB::raw('((ACOS(SIN( ' . $latitude .' * PI() / 180) * SIN(job_latitude * PI() / 180) + COS(' . $latitude .' * PI() / 180) * COS(job_latitude * PI() / 180) * COS((' . $longitude .' - job_longitude) * PI() / 180)) * 180 / PI()) * 60 * 1.1515) as distance') );
        $query->having('distance', '<=', $distance);
        $jobs = $query // ->where('sender_id', '!=', $user_id)
            ->where('status', 'Pending')
            ->orderBy('distance', 'asc')
            ->get();

        $jobs = new JobCollection($jobs);

        return self::success("near by job", ['jobs' => $jobs]);

    }

    public function deliveryJobs(Request $request){

        $user_id = \auth()->user()->id;
        $data = $request->all();

        $validator = \Validator::make($request->all(), [
            'deliverer_id' => 'required',
//            'status' => ['required' => 'array'],
        ]);

        if ($validator->fails()) {
            return self::failure($validator->errors()->first());
        };

        $jobs = Job::where('receiver_id', $data['deliverer_id'])->where(function ($q) use ($data){
            if(isset($data['status'])){
                $q->whereIn('status', $data['status']);
            }else{
                $q->where('status', '!=', 'Pending')->where('status', '!=', 'Delivered');
            }


        })->get();
        $jobs = new JobCollection($jobs);

        return self::success("Delivery jobs", ['jobs' => $jobs]);

    }

    public function addJob(Request $request, Helper $helper){

        $user_id = \auth()->user()->id;
        $data = $request->all();

        $validator = \Validator::make($request->all(), [
            'job_latitude' => 'required',
            'job_longitude' => 'required',
            'job_address' => "required",
            'delivery_address' => "required",
            'job_price' => "required",
            'priority' => "required",
            'item_category' => "required",
            'package_size' => "required",
            'source_address_appartment' => "required",
            'delivery_address_appartment' => "required",
        ], [
            "job_latitude" => "Job Source Coordinates missing",
            "job_longitude" => "Job Source Coordinates missing",
            "delivery_latitude" => "Job Destination Coordinates missing",
            "delivery_longitude" => "Job Destination Coordinates missing",
            "priority" => "Job Delivery Type required",
            'package_size' => "Delivery Vehicle required",
        ]);

        if ($validator->fails()) {
            return self::failure($validator->errors()->first());
        };

        $data['status'] = config('enums.job.status.PENDING');
        $job = new Job($data);
        $job->security_code = Helper::incrementalHash(6);
        $job->save();

        // update job status in table
        $this->updateJobStatus($job);

        // save photos of job


        $photos_urls = isset($data['photos_urls']) ? $data['photos_urls'] : [];

        foreach ($photos_urls as $url){
            Joburls::create([
               'owner_id' => $user_id,
               'job_id' => $job->id,
               'firebase_url' => $url
            ]);
        }

        $user_id = \auth()->user()->id;
        $receiver_id = null;
        $otpnumber = OtpNumbers::where('phone_number', $data['receiver_contact'] )->first();
        if($otpnumber){
            $otp_number_user_id = $otpnumber->user_id;
            if(isset($otp_number_user_id)){
                $receiver_id = $otp_number_user_id;
            }
        }else{

            $hash = $helper::generateOtp();
            OtpNumbers::create(['phone_number' => $data['receiver_contact'], 'is_verified' => 0, 'otp_code' => $hash, 'expires' => Carbon::now()->addMinutes(5) ]);

        }

        $job->update([
            'sender_id' => $user_id,
            'receiver_id' => $receiver_id
        ]);

        return self::success("New Job Created", [ 'jobId' => $job->id ] );

    }

    public function postedJobs(Request $request){

        $data = $request->all();

        $validator = \Validator::make($request->all(), [
            'jobtype' => ['required' => 'in:active,complete'],
        ]);

        if ($validator->fails()) {
            return self::failure($validator->errors()->first());
        };



        $user_id = \auth()->user()->id;
        $offset = $request->offset ? $request->offset : 0;
        $query = Job::query();

        if($request->jobtype == 'complete'){
            $query->where('status', config('enums.job.status.DELIVERED'));
        }else{
            $query->where('status', '!=', config('enums.job.status.DELIVERED'));
        }
        $query->where('sender_id', $user_id );
        $jobs = $query->orderBy('created_at', 'DESC' , SORT_NATURAL|SORT_FLAG_CASE)
        ->offset($offset)
        ->limit(10)
        ->get();

        $jobs = new JobCollection($jobs);

        return self::success("Posted Jobs", ['jobs' => $jobs]);
    }

    public function updateJob(Request $request){

        $user_id = \auth()->user()->id;
        $data = $request->all();

        $validator = \Validator::make($request->all(), [
            'job_id' => 'required|integer',
            'status' => ['required' => 'in:Pending,Started,Accepted,Delivered,Received,Completed'],
            'latitude' => ['required','regex:/^[-]?(([0-8]?[0-9])\.(\d+))|(90(\.0+)?)$/'],
            'longitude' => ['required','regex:/^[-]?((((1[0-7][0-9])|([0-9]?[0-9]))\.(\d+))|180(\.0+)?)$/']
        ]);

        if ($validator->fails()) {
            return self::failure($validator->errors()->first());
        };

        $job = Job::where('id', $request->job_id)->first();
        if(!$job){
            return self::failure("Invalid Job");
        }

        $job->update([
            'status' => $request->status,
        ]);

        // update job status in table
        $this->updateJobStatus($job, $data["latitude"], $data["longitude"]);

        $job = Job::where('id', $request->job_id)->first();
        $job = new JobResource($job);

        return self::success("Job Updated", [ 'job' => $job ] );

    }

    public function verifyCompletedJob(Request $request){

        $user_id = \auth()->user()->id;
        $data = $request->all();

        $validator = \Validator::make($request->all(), [

resources/views/admin/jobs/create.blade.php
@extends('layouts.app')

@section('main')
<!-- Main Content -->
    <div class="gx-main-content">
        <!--gx-wrapper-->
        <div class="gx-wrapper">
            @include('includes.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="gx-card">
                        <div class="gx-card-header">
                        </div>
                        <div class="gx-card-body">
                            <form class="form-horizontal" action="{{ route('admin.jobs.store') }}" method="POST" enctype="multipart/form-data">
                                {{ csrf_field() }}
                                @include('admin.jobs.form')
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-9 offset-md-2 offset-sm-3">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/gx-wrapper-->

        @include('includes.footer')

    </div>
    <!-- /main content -->

@endsection

resources/views/admin/jobs/edit.blade.php
@extends('layouts.app')

@section('main')
<!-- Main Content -->
    <div class="gx-main-content">
        <!--gx-wrapper-->
        <div class="gx-wrapper">
            @include('includes.breadcrumb')
            <div class="row">
                <div class="col-lg-12">
                    <div class="gx-card">
                        <div class="gx-card-header">
                        </div>
                        <div class="gx-card-body">
                            <form class="form-horizontal" action="{{ route('admin.jobs.update', $job->id) }}" method="POST" enctype="multipart/form-data">
                                {{method_field('PUT')}}
                                {{ csrf_field() }}
                                @include('admin.jobs.form')
                                <div class="form-group row">
                                    <div class="col-md-10 col-sm-9 offset-md-2 offset-sm-3">
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--/gx-wrapper-->

        @include('includes.footer')

    </div>
    <!-- /main content -->

@endsection

resources/views/admin/jobs/form.blade.php
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Delivery Address</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="delivery_address" value="{{ $job->delivery_address ?? old('delivery_address') }}" name="delivery_address" placeholder="Delivery Address">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Delivery Latitude</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="delivery_latitude" value="{{ $job->delivery_latitude ?? old('delivery_latitude') }}" name="delivery_latitude" placeholder="Delivery Latitude">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Delivery Longitude</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="delivery_longitude" value="{{ $job->delivery_longitude ?? old('delivery_longitude') }}" name="delivery_longitude" placeholder="Delivery Longitude">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Description</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="description" value="{{ $job->description ?? old('description') }}" name="description" placeholder="Description">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Expected Delivery Time</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="expected_delivery_time" value="{{ $job->expected_delivery_time ?? old('expected_delivery_time') }}" name="expected_delivery_time" placeholder="Expected Delivery Time">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Geohash</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="geohash" value="{{ $job->geohash ?? old('geohash') }}" name="geohash" placeholder="Geohash">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Item Category</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="item_job" value="{{ $job->item_job ?? old('item_job') }}" name="item_job" placeholder="Item Category">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Job Address</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="job_address" value="{{ $job->job_address ?? old('job_address') }}" name="job_address" placeholder="Job Address">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Job Latitude</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="job_latitude" value="{{ $job->job_latitude ?? old('job_latitude') }}" name="job_latitude" placeholder="Job Latitude">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Job Price</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="job_price" value="{{ $job->job_price ?? old('job_price') }}" name="job_price" placeholder="Job Price">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Package Size</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="package_size" value="{{ $job->package_size ?? old('package_size') }}" name="package_size" placeholder="Package Size">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Posted At</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="posted_at" value="{{ $job->posted_at ?? old('posted_at') }}" name="posted_at" placeholder="Posted At">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Posted Id</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="posted_id" value="{{ $job->posted_id ?? old('posted_id') }}" name="posted_id" placeholder="Posted Id">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Priority</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="priority" value="{{ $job->priority ?? old('priority') }}" name="priority" placeholder="Priority">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Receiver Instructions</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="receiver_instructions" value="{{ $job->receiver_instructions ?? old('receiver_instructions') }}" name="receiver_instructions" placeholder="Receiver Instructions">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Security Code</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="security_code" value="{{ $job->security_code ?? old('security_code') }}" name="security_code" placeholder="Security Code">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Status</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="status" value="{{ $job->status ?? old('status') }}" name="status" placeholder="Status">
    </div>
</div>
<div class="line-dashed"></div>
<div class="form-group row">
    <label class="col-md-2 col-sm-3 control-label">Document Id</label>
    <div class="col-md-10 col-sm-9">
        <input type="text" class="form-control" id="document_id" value="{{ $job->document_id ?? old('document_id') }}" name="document_id" placeholder="Document Id">
    </div>
</div>
<div class="line-dashed"></div>

resources/views/admin/jobs/index.blade.php
@extends('admin.index')

@section('content')
    <!-- Main Content -->
    <div class="gx-main-content">
        <!--gx-wrapper-->
        <div class="gx-wrapper">
            <div class="animated slideInUpTiny animation-duration-3">

                <section class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1>Jobs</h1>
                            </div>
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                                    <li class="breadcrumb-item active">Jobs</li>
                                </ol>
                            </div>
                        </div>
                    </div><!-- /.container-fluid -->
                </section>
                <section class="content">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="card">
                                    <div class="card-header">
                                        <h3 class="card-title">List of all jobs</h3>
                                    </div>
                                    <!-- /.card-header -->
                                    <div class="card-body">
                                        <table class="table">
                                            <thead>
                                            <th>Delivery Address</th>
                                            <th>Expected Delivery Time</th>
                                            <th>Item Category</th>
                                            <th>Job Address</th>
                                            <th>Job Price</th>
                                            <th>Posted At</th>
                                            <th>Sender</th>
                                            <th>Receiver</th>
                                            <th>Priority</th>
                                            <th>Status</th>
                                            <th>Action</th>
                                            </thead>
                                            <tbody>
                                            @foreach ($records as $record)
                                                <tr class="gradeX">
                                                    <td><a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{$record->delivery_latitude}},{{$record->delivery_longitude}}">
                                                        {{$record->delivery_address}}
                                                        </a>
                                                    </td>
                                                    <td>{{date('M, d, Y H:i:s', strtotime($record->expected_delivery_time))}}</td>
                                                    <td>{{$record->item_category}}</td>
                                                    <td>
                                                        <a target="_blank" href="https://www.google.com/maps/search/?api=1&query={{$record->job_latitude}},{{$record->job_longitude}}">
                                                            {{$record->job_address}}
                                                        </a>
                                                    </td>
                                                    <td>$ {{$record->job_price}}</td>
                                                    <td>{{date('M, d, Y', strtotime($record->created_at))}}</td>
                                                    <td> @if($record->sender) {{$record->sender->first_name}} {{$record->sender->last_name}} @endif</td>
                                                    <td> @if($record->receiver) {{$record->receiver->first_name}} {{$record->receiver->last_name}} @endif</td>
                                                    <td>{{$record->priority}}</td>
                                                    <td>{{$record->status}}</td>
                                                    <td>
                                                        <a href="{{url('admin/jobs/'.$record->id)}}"><i class="fas fa-info-circle"></i></a>

                                                    </td>

                                            @endforeach


                                            </tbody>
                                        </table>
                                    </div>
                                    <!-- /.card-body -->

                                </div>
                                <!-- /.card -->
                            </div>
                            <!-- /.col -->


                        </div>

                        <div class="row">
                            @if (count($records))
                                <div class="col-sm-4 hidden-xs">
                                    <small class="text-muted inline m-t-sm m-b-sm">Showing {!! $records->firstItem() . '-' . $records->lastItem() !!} of {!! $records->total() !!} record(s)</small>
                                </div>
                                <div class="col-sm-3 text-center">
                                </div>
                                <div class="col-sm-5 text-right text-center-xs">
                                    {{ $records->links() }}
                                </div>
                            @else
                                <div class="col-sm-12 text-center">
                                    <small class="text-muted inline m-t-sm m-b-sm">No records found.</small>
                                </div>
                            @endif
                        </div>

                        <!-- /.row -->
                    </div><!-- /.container-fluid -->
                </section>
            </div>
        </div>
        <!--/gx-wrapper-->
        @include('includes.footer')
    </div>


    <!-- /main content -->
@endsection